android {
    flavorDimensions += "flavor-type"

    productFlavors {
        di {
            dimension "flavor-type"
            applicationId "com.empoweredman.empoweredman"
            resValue "string", "app_name", "Empowered Man DI"
        }
        api {
            dimension "flavor-type"
            applicationId "com.empoweredman.empoweredman.api"
            resValue "string", "app_name", "Empowered Man API"
        }
        production {
            dimension "flavor-type"
            applicationId "com.empoweredman.empoweredman.au"
            resValue "string", "app_name", "Empowered Man"
        }
    }
}